<?php

namespace AppBundle\Repository;

/**
 * HumanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HumanoRepository extends \Doctrine\ORM\EntityRepository
{
}
