<?php

namespace AppBundle\Repository;

/**
 * MascotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MascotaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByChip($chip)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT m
                FROM AppBundle:Mascota m 
                WHERE m.chip = '{$chip}'"
            )
            ->getArrayResult();
    }
}
